name: Unit Tests # name of the test

on:
 push:
   branches: [ StarterCodeDrafts ]  # or 'master' if that's your primary branch name
 pull_request:
   branches: [ StarterCodeDrafts ] # the Github Action will activate "on" the event that you "push" to the repo

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
        working-directory: ./client
      - name: Unit Test
        run: npm test
        working-directory: ./client